packages:
  - test # 存放我们组件测试的时候的代码
  - docs # 存放我们组件文档的
  - package/**
allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  vue-demi: set this to true or false
