const { defineProps, defineSlots, defineEmits, defineExpose, defineModel, defineOptions, withDefaults, } = await import('vue');
const __VLS_fnComponent = (await import('vue')).defineComponent({});
;
let __VLS_functionalComponentProps;
function __VLS_template() {
    let __VLS_ctx;
    let __VLS_otherComponents;
    let __VLS_own;
    let __VLS_localComponents;
    let __VLS_components;
    let __VLS_styleScopedClasses;
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: ("main") }));
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: ("section") }));
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: ("title") }));
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: ("content") }));
    const __VLS_0 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_1 = __VLS_asFunctionalComponent(__VLS_0, new __VLS_0({ type: ("primary"), content: ("PRIMARY"), }));
    const __VLS_2 = __VLS_1({ type: ("primary"), content: ("PRIMARY"), }, ...__VLS_functionalComponentArgsRest(__VLS_1));
    ({}({ type: ("primary"), content: ("PRIMARY"), }));
    const __VLS_5 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_0, __VLS_2));
    __VLS_nonNullable(__VLS_5.slots).default;
    const __VLS_6 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_7 = __VLS_asFunctionalComponent(__VLS_6, new __VLS_6({ type: ("success"), content: ("SUCCESS"), }));
    const __VLS_8 = __VLS_7({ type: ("success"), content: ("SUCCESS"), }, ...__VLS_functionalComponentArgsRest(__VLS_7));
    ({}({ type: ("success"), content: ("SUCCESS"), }));
    const __VLS_11 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_6, __VLS_8));
    __VLS_nonNullable(__VLS_11.slots).default;
    const __VLS_12 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_13 = __VLS_asFunctionalComponent(__VLS_12, new __VLS_12({ type: ("warning"), content: ("WARNING"), }));
    const __VLS_14 = __VLS_13({ type: ("warning"), content: ("WARNING"), }, ...__VLS_functionalComponentArgsRest(__VLS_13));
    ({}({ type: ("warning"), content: ("WARNING"), }));
    const __VLS_17 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_12, __VLS_14));
    __VLS_nonNullable(__VLS_17.slots).default;
    const __VLS_18 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_19 = __VLS_asFunctionalComponent(__VLS_18, new __VLS_18({ type: ("danger"), content: ("DANGER"), }));
    const __VLS_20 = __VLS_19({ type: ("danger"), content: ("DANGER"), }, ...__VLS_functionalComponentArgsRest(__VLS_19));
    ({}({ type: ("danger"), content: ("DANGER"), }));
    const __VLS_23 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_18, __VLS_20));
    __VLS_nonNullable(__VLS_23.slots).default;
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: ("section") }));
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: ("title") }));
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: ("content") }));
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: ("panel") }));
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)(Object.assign({ class: ("subtitle") }));
    const __VLS_24 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_25 = __VLS_asFunctionalComponent(__VLS_24, new __VLS_24({ type: ("primary"), size: ("large"), content: ("PRIMARY"), }));
    const __VLS_26 = __VLS_25({ type: ("primary"), size: ("large"), content: ("PRIMARY"), }, ...__VLS_functionalComponentArgsRest(__VLS_25));
    ({}({ type: ("primary"), size: ("large"), content: ("PRIMARY"), }));
    const __VLS_29 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_24, __VLS_26));
    __VLS_nonNullable(__VLS_29.slots).default;
    const __VLS_30 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_31 = __VLS_asFunctionalComponent(__VLS_30, new __VLS_30({ type: ("success"), size: ("large"), content: ("SUCCESS"), }));
    const __VLS_32 = __VLS_31({ type: ("success"), size: ("large"), content: ("SUCCESS"), }, ...__VLS_functionalComponentArgsRest(__VLS_31));
    ({}({ type: ("success"), size: ("large"), content: ("SUCCESS"), }));
    const __VLS_35 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_30, __VLS_32));
    __VLS_nonNullable(__VLS_35.slots).default;
    const __VLS_36 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_37 = __VLS_asFunctionalComponent(__VLS_36, new __VLS_36({ type: ("warning"), size: ("large"), content: ("WARNING"), }));
    const __VLS_38 = __VLS_37({ type: ("warning"), size: ("large"), content: ("WARNING"), }, ...__VLS_functionalComponentArgsRest(__VLS_37));
    ({}({ type: ("warning"), size: ("large"), content: ("WARNING"), }));
    const __VLS_41 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_36, __VLS_38));
    __VLS_nonNullable(__VLS_41.slots).default;
    const __VLS_42 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_43 = __VLS_asFunctionalComponent(__VLS_42, new __VLS_42({ type: ("danger"), size: ("large"), content: ("DANGER"), }));
    const __VLS_44 = __VLS_43({ type: ("danger"), size: ("large"), content: ("DANGER"), }, ...__VLS_functionalComponentArgsRest(__VLS_43));
    ({}({ type: ("danger"), size: ("large"), content: ("DANGER"), }));
    const __VLS_47 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_42, __VLS_44));
    __VLS_nonNullable(__VLS_47.slots).default;
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: ("panel") }));
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)(Object.assign({ class: ("subtitle") }));
    const __VLS_48 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_49 = __VLS_asFunctionalComponent(__VLS_48, new __VLS_48({ type: ("primary"), size: ("default"), content: ("PRIMARY"), }));
    const __VLS_50 = __VLS_49({ type: ("primary"), size: ("default"), content: ("PRIMARY"), }, ...__VLS_functionalComponentArgsRest(__VLS_49));
    ({}({ type: ("primary"), size: ("default"), content: ("PRIMARY"), }));
    const __VLS_53 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_48, __VLS_50));
    __VLS_nonNullable(__VLS_53.slots).default;
    const __VLS_54 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_55 = __VLS_asFunctionalComponent(__VLS_54, new __VLS_54({ type: ("success"), size: ("default"), content: ("SUCCESS"), }));
    const __VLS_56 = __VLS_55({ type: ("success"), size: ("default"), content: ("SUCCESS"), }, ...__VLS_functionalComponentArgsRest(__VLS_55));
    ({}({ type: ("success"), size: ("default"), content: ("SUCCESS"), }));
    const __VLS_59 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_54, __VLS_56));
    __VLS_nonNullable(__VLS_59.slots).default;
    const __VLS_60 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_61 = __VLS_asFunctionalComponent(__VLS_60, new __VLS_60({ type: ("warning"), size: ("default"), content: ("WARNING"), }));
    const __VLS_62 = __VLS_61({ type: ("warning"), size: ("default"), content: ("WARNING"), }, ...__VLS_functionalComponentArgsRest(__VLS_61));
    ({}({ type: ("warning"), size: ("default"), content: ("WARNING"), }));
    const __VLS_65 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_60, __VLS_62));
    __VLS_nonNullable(__VLS_65.slots).default;
    const __VLS_66 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_67 = __VLS_asFunctionalComponent(__VLS_66, new __VLS_66({ type: ("danger"), size: ("default"), content: ("DANGER"), }));
    const __VLS_68 = __VLS_67({ type: ("danger"), size: ("default"), content: ("DANGER"), }, ...__VLS_functionalComponentArgsRest(__VLS_67));
    ({}({ type: ("danger"), size: ("default"), content: ("DANGER"), }));
    const __VLS_71 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_66, __VLS_68));
    __VLS_nonNullable(__VLS_71.slots).default;
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: ("panel") }));
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)(Object.assign({ class: ("subtitle") }));
    const __VLS_72 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_73 = __VLS_asFunctionalComponent(__VLS_72, new __VLS_72({ type: ("primary"), size: ("small"), content: ("PRIMARY"), }));
    const __VLS_74 = __VLS_73({ type: ("primary"), size: ("small"), content: ("PRIMARY"), }, ...__VLS_functionalComponentArgsRest(__VLS_73));
    ({}({ type: ("primary"), size: ("small"), content: ("PRIMARY"), }));
    const __VLS_77 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_72, __VLS_74));
    __VLS_nonNullable(__VLS_77.slots).default;
    const __VLS_78 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_79 = __VLS_asFunctionalComponent(__VLS_78, new __VLS_78({ type: ("success"), size: ("small"), content: ("SUCCESS"), }));
    const __VLS_80 = __VLS_79({ type: ("success"), size: ("small"), content: ("SUCCESS"), }, ...__VLS_functionalComponentArgsRest(__VLS_79));
    ({}({ type: ("success"), size: ("small"), content: ("SUCCESS"), }));
    const __VLS_83 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_78, __VLS_80));
    __VLS_nonNullable(__VLS_83.slots).default;
    const __VLS_84 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_85 = __VLS_asFunctionalComponent(__VLS_84, new __VLS_84({ type: ("warning"), size: ("small"), content: ("WARNING"), }));
    const __VLS_86 = __VLS_85({ type: ("warning"), size: ("small"), content: ("WARNING"), }, ...__VLS_functionalComponentArgsRest(__VLS_85));
    ({}({ type: ("warning"), size: ("small"), content: ("WARNING"), }));
    const __VLS_89 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_84, __VLS_86));
    __VLS_nonNullable(__VLS_89.slots).default;
    const __VLS_90 = {}
        .CpButton;
    ({}.CpButton);
    ({}.CpButton);
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    __VLS_components.CpButton;
    __VLS_components.cpButton;
    [CpButton, CpButton,];
    const __VLS_91 = __VLS_asFunctionalComponent(__VLS_90, new __VLS_90({ type: ("danger"), size: ("small"), content: ("DANGER"), }));
    const __VLS_92 = __VLS_91({ type: ("danger"), size: ("small"), content: ("DANGER"), }, ...__VLS_functionalComponentArgsRest(__VLS_91));
    ({}({ type: ("danger"), size: ("small"), content: ("DANGER"), }));
    const __VLS_95 = __VLS_nonNullable(__VLS_pickFunctionalComponentCtx(__VLS_90, __VLS_92));
    __VLS_nonNullable(__VLS_95.slots).default;
    if (typeof __VLS_styleScopedClasses === 'object' && !Array.isArray(__VLS_styleScopedClasses)) {
        __VLS_styleScopedClasses['main'];
        __VLS_styleScopedClasses['section'];
        __VLS_styleScopedClasses['title'];
        __VLS_styleScopedClasses['content'];
        __VLS_styleScopedClasses['section'];
        __VLS_styleScopedClasses['title'];
        __VLS_styleScopedClasses['content'];
        __VLS_styleScopedClasses['panel'];
        __VLS_styleScopedClasses['subtitle'];
        __VLS_styleScopedClasses['panel'];
        __VLS_styleScopedClasses['subtitle'];
        __VLS_styleScopedClasses['panel'];
        __VLS_styleScopedClasses['subtitle'];
    }
    var __VLS_slots;
    return __VLS_slots;
    const __VLS_componentsOption = {};
    let __VLS_name;
    let __VLS_defineComponent;
    const __VLS_internalComponent = __VLS_defineComponent({
        setup() {
            return {};
        },
    });
}
export default (await import('vue')).defineComponent({
    setup() {
        return {};
    },
});
;
//# sourceMappingURL=App.vue.js.map